"""Add recipe columns

Revision ID: 4ec77be6df53
Revises: 066cbc49aae0
Create Date: 2026-06-01 17:21:34.353619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec77be6df53'
down_revision = '066cbc49aae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('category')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
